# Generated by Django 6.0.7 on 2026-07-11 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=12, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('classe', models.CharField(choices=[('acao', 'Ação'), ('fii', 'FII'), ('renda_fixa', 'Renda Fixa'), ('etf', 'ETF')], max_length=12)),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=6, max_digits=18)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cotacao', to='portfolio.ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('venda', 'Venda')], max_length=6)),
                ('quantidade', models.DecimalField(decimal_places=6, max_digits=18)),
                ('preco_unitario', models.DecimalField(decimal_places=6, max_digits=18)),
                ('data', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operacoes', to='portfolio.ativo')),
            ],
            options={
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
